### ISSUE TITLE
No date and time in Sprint Race

### ISSUE THREAD

**Issue by didoub74-off** [Rafacv23/F1-api#8]
Hi,
It seems, there's no date and time in the sprint race endpoints, compared to the qualy (even sprint qualy)

[Here to take a look](https://f1connectapi.vercel.app/api/2024/23/sprint/race)

Can you check.
Thx

**Comment by Rafacv23** [comment]
Fixed!

now:
![image](https://github.com/user-attachments/assets/f1f79e2f-eb69-42a4-830a-66e833030172)

before:
![image](https://github.com/user-attachments/assets/8c230fe3-090c-4cd1-a012-d577cf5bfcf7)

Endpoint: [https://f1connectapi.vercel.app/api/2024/23/sprint/race](url)

Let me know if you see any problem!

**Comment by didoub74-off** [comment]
Great thanks.

**Comment by Rafacv23** [comment]
@all-contributors please add @didoub74-off for bug
